/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import simulation.ProcessusPoisson;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import loismathematiques.Exponentielle;
/**
 *
 * @author jerem
 */
public class Simulation extends javax.swing.JFrame {
    
    private int timer = 50;
    private int token;
    private ArrayList<ProcessusPoisson> tabProcPoisson;
    private int nbMissions;
    private int dureeMission;
    private int dureeMoyenneEntrePannes;
    private int nbPiecesRechanges;

    /**
     * Creates new form Simulation
     */
    public Simulation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tbDuree = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tbDuree1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tbDuree2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tbDuree3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btLancerSimulation = new javax.swing.JButton();
        btLessFrequenceTimer = new javax.swing.JButton();
        btAddFrequenceTimer = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tbDuree7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btLancerSimulation1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tbDuree4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        tbDuree6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tbDuree8 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Simulation d'un vol d'avion");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Ordinateurs de bords");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(284, 284, 284))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Durée d'un vol :");

        tbDuree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbDureeKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("heures");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Durée moyenne entre deux pannes :");

        tbDuree1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbDuree1KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("heures");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nombre de vols :");

        tbDuree2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbDuree2KeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("vols");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nombre de pièces de rechanges :");

        tbDuree3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbDuree3KeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("pièces");

        btLancerSimulation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btLancerSimulation.setText("LANCER LA SIMULATION");
        //btLancerSimulation.setEnabled(true);
        btLancerSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLancerSimulationActionPerformed(evt);
            }
        });

        btLessFrequenceTimer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btLessFrequenceTimer.setText("-");
        btLessFrequenceTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLessFrequenceTimerActionPerformed(evt);
            }
        });

        btAddFrequenceTimer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAddFrequenceTimer.setText("+");
        btAddFrequenceTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddFrequenceTimerActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Vitesse de la simulation :");

        tbDuree7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbDuree7KeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("vols");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Nombre de vols visibles en même temps :");

        btLancerSimulation1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btLancerSimulation1.setText("LANCER LA SIMULATION INSTANTANNEE");
        btLancerSimulation1.setEnabled(false);
        btLancerSimulation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLancerSimulation1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(tbDuree7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tbDuree, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(19, 19, 19)
                                .addComponent(tbDuree2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(tbDuree3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        
                                       
                                        .addGap(57, 57, 57))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tbDuree1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addComponent(btLancerSimulation1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbDuree7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tbDuree2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tbDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tbDuree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tbDuree3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLancerSimulation1)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Paramètres du vol :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 272, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 510, 420));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Résultats du vol :");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Fiabilité :");

        tbDuree4.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Récapitulatif des vols :");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Nombre de pannes", "MTBF", "Résultat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("MTBF :");

        tbDuree6.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("%");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("(Nombre théorique de pannes sur un vol :");

        tbDuree8.setEditable(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("jours");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("pannes)");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbDuree4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbDuree6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbDuree8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tbDuree8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(34, 34, 34)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tbDuree4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(tbDuree6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 590, 420));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 10, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLessFrequenceTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLessFrequenceTimerActionPerformed
        this.timer += 10;
        for (int i=0;i<tabProcPoisson.size();i++){
            tabProcPoisson.get(i).setTimer(timer);
        }
    }//GEN-LAST:event_btLessFrequenceTimerActionPerformed

    private void btAddFrequenceTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddFrequenceTimerActionPerformed
        this.timer = this.timer-10<=0 ? 1 : this.timer-10;
        for (int i=0;i<tabProcPoisson.size();i++){
            tabProcPoisson.get(i).setTimer(timer);
        }
    }//GEN-LAST:event_btAddFrequenceTimerActionPerformed

    private void btLancerSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLancerSimulationActionPerformed
        //Bloquage de tout les boutons et champs de saisie pour le lancement de simulation
        btLancerSimulation.setEnabled(true);
        btLancerSimulation1.setEnabled(false);
        tbDuree.setEnabled(true);
        tbDuree1.setEnabled(true);
        tbDuree2.setEnabled(true);
        tbDuree3.setEnabled(true);
        tbDuree7.setEnabled(true);
        //Reinitialisation du tableau et des champs finaux
        /*DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);*/
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jTable1.getRowSorter().setSortKeys(null);
        tbDuree4.setText("");
        //tbDuree5.setText("");
        tbDuree6.setText("");
        tbDuree8.setText("");
        //Initialisation propres a la simu
        tabProcPoisson = new ArrayList<>();
        //CREER LE THREAD ET LE LANCER
        Thread thread = new Thread(new Runnable() {
            @Override public void run(){myThreadVisuel();}
        });
        thread.start();
        //Renseignement des champs finaux theoriques
        tbDuree8.setText(Double.toString(((double)Math.round((((double)dureeMission)/dureeMoyenneEntrePannes)* 100000)/100000)));
        Exponentielle exp = new Exponentielle(((double)dureeMoyenneEntrePannes)/dureeMission);
        //tbDuree5.setText(Double.toString(((double)Math.round((exp.pQueXSoitInferieurA(nbPiecesRechanges))* 10000000)/100000)));
    }//GEN-LAST:event_btLancerSimulationActionPerformed

    private void tbDureeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDureeKeyReleased
        //SAISIE DUREE D'UNE MISSION 
        try{
           dureeMission=Integer.parseInt(tbDuree.getText());
        }catch (Exception e){}
        bloquerOuDebloquerLancementSimu();
    }//GEN-LAST:event_tbDureeKeyReleased

    private void tbDuree1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDuree1KeyReleased
        //SAISIE DUREE MOYENNE ENTRE DEUX PANNES
        try{
           dureeMoyenneEntrePannes=Integer.parseInt(tbDuree1.getText());
        }catch (Exception e){}
        bloquerOuDebloquerLancementSimu();
    }//GEN-LAST:event_tbDuree1KeyReleased

    private void tbDuree3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDuree3KeyReleased
        //SAISIE NOMBRE DE PIECES DE RECHANGES
        try{
           nbPiecesRechanges=Integer.parseInt(tbDuree3.getText());
        }catch (Exception e){}
        bloquerOuDebloquerLancementSimu();
    }//GEN-LAST:event_tbDuree3KeyReleased

    private void tbDuree2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDuree2KeyReleased
        //SAISIE NOMBRE DE MISSIONS
        try{
           nbMissions= Integer.parseInt(tbDuree2.getText());
        }catch (Exception e){}
        bloquerOuDebloquerLancementSimu();
    }//GEN-LAST:event_tbDuree2KeyReleased

    private void tbDuree7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDuree7KeyReleased
        //SAISIE NOMBRE DE MISSIONS MAXIMALES QUE L'ON PEUT VOIR EN MEME TEMPS
        try{
           token= Integer.parseInt(tbDuree7.getText());
        }catch (Exception e){}
        bloquerOuDebloquerLancementSimu();
    }//GEN-LAST:event_tbDuree7KeyReleased

    private void btLancerSimulation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLancerSimulation1ActionPerformed
        //Bloquage de tout les boutons et champs de saisie pour le lancement de simulation instantannÃ©e
        btLancerSimulation.setEnabled(false);
        btLancerSimulation1.setEnabled(false);
        tbDuree.setEnabled(false);
        tbDuree1.setEnabled(false);
        tbDuree2.setEnabled(false);
        tbDuree3.setEnabled(false);
        tbDuree7.setEnabled(false);
        //Reinitialisation du tableau et des champs finaux
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jTable1.getRowSorter().setSortKeys(null);
        tbDuree4.setText("");
        //tbDuree5.setText("");
        tbDuree6.setText("");
        tbDuree8.setText("");
        //CREER LE THREAD ET LE LANCER
        Thread thread = new Thread(new Runnable() {
            @Override public void run(){myThreadNonVisuel();}
        });
        thread.start();
        tbDuree8.setText(Double.toString(((double)Math.round((((double)dureeMission)/dureeMoyenneEntrePannes)* 100000)/100000)));
        Exponentielle exp = new Exponentielle(((double)dureeMoyenneEntrePannes)/dureeMission);
        //tbDuree5.setText(Double.toString(((double)Math.round((exp.pQueXSoitInferieurA(nbPiecesRechanges))* 10000000)/100000)));
    }//GEN-LAST:event_btLancerSimulation1ActionPerformed
    
    private void bloquerOuDebloquerLancementSimu(){
        //System.out.println(dureeMission + " " + dureeMoyenneEntrePannes + " " + nbPiecesRechanges + " " + nbMissions + " " + token);
        if((dureeMission>0) && (dureeMoyenneEntrePannes>0) && (nbPiecesRechanges>0) && (nbMissions>0) && (token>0)){
            btLancerSimulation.setEnabled(true);
        } else {
            btLancerSimulation.setEnabled(false);
        }
        if((dureeMission>0) && (dureeMoyenneEntrePannes>0) && (nbPiecesRechanges>0) && (nbMissions>0)){
            btLancerSimulation1.setEnabled(true);
        } else {
            btLancerSimulation1.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Simulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddFrequenceTimer;
    private javax.swing.JButton btLancerSimulation;
    private javax.swing.JButton btLancerSimulation1;
    private javax.swing.JButton btLessFrequenceTimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tbDuree;
    private javax.swing.JTextField tbDuree1;
    private javax.swing.JTextField tbDuree2;
    private javax.swing.JTextField tbDuree3;
    private javax.swing.JTextField tbDuree4;
    private javax.swing.JTextField tbDuree6;
    private javax.swing.JTextField tbDuree7;
    private javax.swing.JTextField tbDuree8;
    // End of variables declaration//GEN-END:variables
                
    public void myThreadVisuel(){
        //declaration et initialisation
        int nbProcessLaunched=0;
        int nbProcessFinished=0;
        int nbMissionsReussies=0;
        int nbPannesTotal=0;
        double intervalPannesTotal=0;
        //Tant qu'on a pas autant de processus terminÃ© que de missions souhaitees.
        while(nbProcessFinished<nbMissions){
            //Tant qu'on a pas lancÃ© autant de processus que de mission souhaitees
            while(nbProcessLaunched<nbMissions && tabProcPoisson.size()<token){
                //On crÃ©e un processus 
                tabProcPoisson.add(new ProcessusPoisson(1, 1,(((double)1)/dureeMoyenneEntrePannes), this.timer, this.dureeMission));
                //On incrÃ©mente le numero du dernier processus lancÃ©
                nbProcessLaunched++;
            }
            //Tant qu'il reste au moins un processus et que le plus ancien est terminÃ©
            while (tabProcPoisson.size()>0 && tabProcPoisson.get(0).isFinished()){
                //Declaration et initialisation locale
                ArrayList tabIntervalPannes = tabProcPoisson.get(0).getTabIntervalleEvenement();
                double intervalPannesProcessus=0;
                int nbPannes = tabProcPoisson.get(0).getNbTotalEvents();
                nbPannesTotal+=nbPannes;
                for (int i=0;i<tabIntervalPannes.size();i++){
                    intervalPannesProcessus+=(double)tabIntervalPannes.get(i);
                }
                intervalPannesTotal+=intervalPannesProcessus;
                //Ajout au tableau du rÃ©sultat de la mission associÃ©e au processus local
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                if (nbPannes>nbPiecesRechanges) model.addRow(new Object[]{jTable1.getModel().getRowCount()+1,nbPannes,((double)Math.round((intervalPannesProcessus/nbPannes)* 100000)/100000),"Echouée"});
                else {
                    model.addRow(new Object[]{jTable1.getModel().getRowCount()+1,nbPannes,((double)Math.round((intervalPannesProcessus/nbPannes)* 100000)/100000),"RÃ©ussie"});
                    nbMissionsReussies++;
                }
                //On supprime le processus 0, ce qui dÃ©calle automatiquement les autres processus 
                tabProcPoisson.remove(0);
                //On incrÃ©mente le nombre de processus finis
                nbProcessFinished++;
            }
        }
        //Calcul et affichage de la MTBF finale
        tbDuree6.setText(Double.toString(((double)Math.round((intervalPannesTotal/nbPannesTotal)* 100000)/100000)));
        //Calcul et affichage du pourcentage de succÃ¨s final
        tbDuree4.setText(Double.toString(((double)Math.round((((double)nbMissionsReussies)/nbMissions)* 10000000)/100000)));
        //Debloquage de tout les boutons et champs de saisie
        bloquerOuDebloquerLancementSimu();
        tbDuree.setEnabled(true);
        tbDuree1.setEnabled(true);
        tbDuree2.setEnabled(true);
        tbDuree3.setEnabled(true);
        tbDuree7.setEnabled(true);
    }
    public void myThreadNonVisuel(){
        //Declaration et initialisation locale
        Exponentielle exp = new Exponentielle(((double)1)/dureeMoyenneEntrePannes);
        int nbMissionsReussies=0;
        int nbPannesTotal=0;
        double intervalPannesTotal=0;
        int nbMissionsLancees=0;
        ArrayList<Double> tabIntervalPannes = new ArrayList<Double>();
        //Creation de l'ensemble des missions
        while(nbMissionsLancees<nbMissions){
            nbMissionsLancees++;
            //Creation des evenements pour une mission
            double intervalPannesGenereesPourCetteMission=0;
            int nbPannesPourCetteMission=0;
            while(intervalPannesGenereesPourCetteMission<dureeMission){
                double nbGenere = exp.genererNombreSuivantLoi();
                tabIntervalPannes.add(nbGenere);
                if (intervalPannesGenereesPourCetteMission+nbGenere<=dureeMission){
                    intervalPannesGenereesPourCetteMission+=nbGenere;
                    nbPannesPourCetteMission++;
                } else break;
            }
            //Mission terminée
            //Ajout du résultat de cette mission au tableau
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            if (nbPannesPourCetteMission>nbPiecesRechanges) model.addRow(new Object[]{jTable1.getModel().getRowCount()+1,nbPannesPourCetteMission,((double)Math.round((intervalPannesGenereesPourCetteMission/nbPannesPourCetteMission)* 100000)/100000),"EchouÃ©e"});
            else {
                model.addRow(new Object[]{jTable1.getModel().getRowCount()+1,nbPannesPourCetteMission,((double)Math.round((intervalPannesGenereesPourCetteMission/nbPannesPourCetteMission)* 100000)/100000),"Réussie"});
                nbMissionsReussies++;
            }
            nbPannesTotal+=nbPannesPourCetteMission++;
            intervalPannesTotal+=intervalPannesGenereesPourCetteMission;
        }        
        //Renseignement des champs finaux
        tbDuree6.setText(Double.toString(((double)Math.round((intervalPannesTotal/nbPannesTotal)* 100000)/100000)));
        tbDuree4.setText(Double.toString(((double)Math.round((((double)nbMissionsReussies)/nbMissions)* 10000000)/100000)));
        
        //Debloquage de tout les boutons et champs de saisie
        bloquerOuDebloquerLancementSimu();
        tbDuree.setEnabled(true);
        tbDuree1.setEnabled(true);
        tbDuree2.setEnabled(true);
        tbDuree3.setEnabled(true);
        tbDuree7.setEnabled(true);
    }
}
